In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
import jax.numpy as jnp
import jax
import jax.random as random
from flax import linen as nn
import optax
from tqdm import tqdm
from utils import DataLoader
from utils import MLP

In [4]:
key = random.PRNGKey(0) # chiave per random 

f_to_learn = lambda mu, k, l, x: jnp.sin(2*mu*jnp.pi*x) + k + jnp.exp(l*x)
N = 10000

key, subkey = random.split(key) # ogni volta, prima di usare la chiave, la devi dividere
x = random.uniform(subkey, (N,), minval=-10, maxval=10)
key, subkey = random.split(key)
mu = random.uniform(subkey, (N,), minval=-2, maxval=2)
key, subkey = random.split(key)
k = random.uniform(subkey, (N,), minval=-5, maxval=5)
key, subkey = random.split(key)
l = random.uniform(subkey, (N,), minval=-1, maxval=1)

y = f_to_learn(mu, k, l, x) # così generiamo artificialmente un dataset di N punti

In [5]:
X = jnp.stack([mu, k, l, x], axis=1)

In [6]:
X = jnp.stack([mu, k, l, x], axis=1)


split_idx = int(N * 0.8)
X_train, X_test = X[:split_idx], X[split_idx:]
y_train, y_test = y[:split_idx], y[split_idx:]

train_dataloader = DataLoader(X_train, y_train, batch_size=32, shuffle=True)
test_dataloader = DataLoader(X_test, y_test, batch_size=32, shuffle=False)


In [7]:
# Example of iterating through the DataLoader
for data, label in train_dataloader:
    print(data.shape, label.shape)
    break

(32, 4) (32, 1)


In [8]:
targetnetwork = MLP(output_dim=1, hidden_dim=8, num_hidden_layers=1)

In [9]:
x = jnp.ones((1,1)) #Gli input sono SEMPRE (SEMPRE) nel formato (bathc_size, input_dim1, input_dim2, ..., input_dimN)
# In questo caso, batch_size=1, input_dim=1
key = jax.random.PRNGKey(0) # Bisogna sempre passare una key per inizializzare i pesi random
print(targetnetwork.tabulate(key, x)) # Visualizza la struttura del modello, con i pesi inizializzati


                               MLP Summary                               
┏━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓
┃ path    ┃ module ┃ inputs       ┃ outputs      ┃ params               ┃
┡━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩
│         │ MLP    │ float32[1,1] │ float32[1,1] │                      │
├─────────┼────────┼──────────────┼──────────────┼──────────────────────┤
│ Dense_0 │ Dense  │ float32[1,1] │ float32[1,8] │ bias: float32[8]     │
│         │        │              │              │ kernel: float32[1,8] │
│         │        │              │              │                      │
│         │        │              │              │ 16 (64 B)            │
├─────────┼────────┼──────────────┼──────────────┼──────────────────────┤
│ Dense_1 │ Dense  │ float32[1,8] │ float32[1,1] │ bias: float32[1]     │
│         │        │              │              │ kernel: float32[8,1] │
│         │        │              │  

In [10]:
hypernetwork = MLP(output_dim = 25, hidden_dim=8, num_hidden_layers=2) # 25 come i parametri del target network

## First try: only training a single network

In [11]:
key = jax.random.PRNGKey(0)
key, subkey = random.split(key)
toy_data = random.uniform(key, (1000, 1), minval=-3, maxval=3)
toy_label = f_to_learn(0.5, 1.0, 0.1, toy_data)
train_dataloader = DataLoader(toy_data, toy_label, batch_size=32, shuffle=True)

In [12]:
model = MLP(output_dim=1, hidden_dim=8, num_hidden_layers=1)

In [13]:
def mse_loss(preds, targets):
    return jnp.mean((preds - targets) ** 2)

optimizer = optax.adam(learning_rate=1e-3)
params = model.init(jax.random.PRNGKey(0), jnp.zeros((1, 1)))
opt_state = optimizer.init(params)
epochs = 1000

In [14]:
# HO CAPITO GLI ITERATORI LOL
it = iter(train_dataloader)
next(it)

(Array([[ 1.3251486 ],
        [ 1.7259712 ],
        [-1.4758916 ],
        [ 1.886148  ],
        [ 1.1210532 ],
        [-0.7078543 ],
        [ 2.0538845 ],
        [ 0.8367226 ],
        [-2.7543204 ],
        [-2.8492084 ],
        [-1.7900848 ],
        [-1.6452813 ],
        [ 0.29829955],
        [ 2.9617748 ],
        [ 1.2408056 ],
        [-0.33282137],
        [-0.01171947],
        [ 1.8245993 ],
        [-2.411188  ],
        [-2.432755  ],
        [ 0.43191075],
        [ 0.0389936 ],
        [-1.9057281 ],
        [ 2.5203166 ],
        [ 0.5336602 ],
        [ 1.9736738 ],
        [ 0.84615755],
        [-1.7945638 ],
        [ 2.6997862 ],
        [-1.15661   ],
        [-1.8660572 ],
        [ 2.6787367 ]], dtype=float32),
 Array([[1.2888119 ],
        [1.4299663 ],
        [2.8599188 ],
        [1.8574771 ],
        [1.7474318 ],
        [1.1373932 ],
        [2.3964782 ],
        [2.5780232 ],
        [1.0617999 ],
        [1.2958694 ],
        [2.4487953 ],
     

In [15]:
def train_step(model, params, opt_state, loss, optimizer, x, y, key=None):
    loss_fn = lambda p, x, y: loss(model.apply(p, x), y)
    loss, grad = jax.value_and_grad(loss_fn)(params, x, y)
    
    updates, opt_state = optimizer.update(grad, opt_state, params)
    params = optax.apply_updates(params, updates)

    return params, opt_state, loss

train_step = jax.jit(train_step, static_argnames=('model', 'loss', 'optimizer'))

for epoch in tqdm(range(epochs)):
    epoch_loss = 0.0
    for data, label in train_dataloader:
        params, opt_state, loss = train_step(model = model, params = params, opt_state = opt_state, loss = mse_loss, optimizer = optimizer, x = data, y = label)
        epoch_loss += loss
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {epoch_loss / len(train_dataloader)}")

print(f"Final loss: {epoch_loss / len(train_dataloader)}")

# TRAINA, POI VEDIAMO SE OVERFITTA CON UN TEST SET

  0%|          | 2/1000 [00:01<11:08,  1.49it/s]

Epoch 0, Loss: 3.7409934997558594


  1%|          | 12/1000 [00:02<02:13,  7.39it/s]

Epoch 10, Loss: 1.0597807168960571


  2%|▏         | 22/1000 [00:04<01:54,  8.54it/s]

Epoch 20, Loss: 0.8475213646888733


  3%|▎         | 32/1000 [00:05<01:48,  8.96it/s]

Epoch 30, Loss: 0.678503692150116


  4%|▍         | 42/1000 [00:06<01:47,  8.90it/s]

Epoch 40, Loss: 0.5686262249946594


  5%|▌         | 52/1000 [00:07<01:47,  8.85it/s]

Epoch 50, Loss: 0.47054120898246765


  6%|▌         | 62/1000 [00:08<01:45,  8.92it/s]

Epoch 60, Loss: 0.437522828578949


  7%|▋         | 72/1000 [00:09<01:42,  9.06it/s]

Epoch 70, Loss: 0.41536298394203186


  8%|▊         | 82/1000 [00:10<01:45,  8.68it/s]

Epoch 80, Loss: 0.39207303524017334


  9%|▉         | 92/1000 [00:12<01:54,  7.95it/s]

Epoch 90, Loss: 0.3721752166748047


 10%|█         | 102/1000 [00:13<01:54,  7.84it/s]

Epoch 100, Loss: 0.3569287359714508


 11%|█         | 112/1000 [00:14<02:23,  6.21it/s]

Epoch 110, Loss: 0.3435188829898834


 12%|█▏        | 122/1000 [00:16<01:56,  7.53it/s]

Epoch 120, Loss: 0.3312161862850189


 13%|█▎        | 132/1000 [00:17<01:41,  8.59it/s]

Epoch 130, Loss: 0.3203343152999878


 14%|█▍        | 142/1000 [00:18<01:35,  8.96it/s]

Epoch 140, Loss: 0.31050172448158264


 15%|█▌        | 152/1000 [00:19<01:36,  8.82it/s]

Epoch 150, Loss: 0.30179378390312195


 16%|█▌        | 162/1000 [00:20<01:34,  8.84it/s]

Epoch 160, Loss: 0.29402658343315125


 17%|█▋        | 172/1000 [00:22<01:32,  8.96it/s]

Epoch 170, Loss: 0.2871979773044586


 18%|█▊        | 182/1000 [00:23<01:31,  8.98it/s]

Epoch 180, Loss: 0.2810569107532501


 19%|█▉        | 192/1000 [00:24<01:29,  8.99it/s]

Epoch 190, Loss: 0.2754061222076416


 20%|██        | 202/1000 [00:25<01:33,  8.53it/s]

Epoch 200, Loss: 0.27010390162467957


 21%|██        | 212/1000 [00:26<01:28,  8.94it/s]

Epoch 210, Loss: 0.2651025056838989


 22%|██▏       | 222/1000 [00:27<01:28,  8.80it/s]

Epoch 220, Loss: 0.2603227496147156


 23%|██▎       | 232/1000 [00:29<01:25,  8.94it/s]

Epoch 230, Loss: 0.2557600140571594


 24%|██▍       | 242/1000 [00:30<01:26,  8.80it/s]

Epoch 240, Loss: 0.2513675391674042


 25%|██▌       | 252/1000 [00:31<01:42,  7.28it/s]

Epoch 250, Loss: 0.24713066220283508


 26%|██▌       | 262/1000 [00:32<01:27,  8.48it/s]

Epoch 260, Loss: 0.2430351972579956


 27%|██▋       | 272/1000 [00:34<01:39,  7.34it/s]

Epoch 270, Loss: 0.23906441032886505


 28%|██▊       | 282/1000 [00:35<01:29,  8.06it/s]

Epoch 280, Loss: 0.23521244525909424


 29%|██▉       | 292/1000 [00:36<01:20,  8.76it/s]

Epoch 290, Loss: 0.23146075010299683


 30%|███       | 302/1000 [00:37<01:18,  8.92it/s]

Epoch 300, Loss: 0.22765043377876282


 31%|███       | 312/1000 [00:38<01:16,  8.96it/s]

Epoch 310, Loss: 0.22316774725914001


 32%|███▏      | 322/1000 [00:39<01:16,  8.85it/s]

Epoch 320, Loss: 0.21897543966770172


 33%|███▎      | 332/1000 [00:40<01:13,  9.03it/s]

Epoch 330, Loss: 0.2147229015827179


 34%|███▍      | 342/1000 [00:42<01:12,  9.04it/s]

Epoch 340, Loss: 0.2104337215423584


 35%|███▌      | 352/1000 [00:43<01:16,  8.51it/s]

Epoch 350, Loss: 0.2061324268579483


 36%|███▌      | 362/1000 [00:44<01:11,  8.93it/s]

Epoch 360, Loss: 0.20186802744865417


 37%|███▋      | 372/1000 [00:45<01:09,  8.99it/s]

Epoch 370, Loss: 0.19766761362552643


 38%|███▊      | 382/1000 [00:46<01:16,  8.09it/s]

Epoch 380, Loss: 0.19353730976581573


 39%|███▉      | 392/1000 [00:47<01:08,  8.84it/s]

Epoch 390, Loss: 0.1895001232624054


 40%|████      | 402/1000 [00:49<01:07,  8.89it/s]

Epoch 400, Loss: 0.18555983901023865


 41%|████      | 412/1000 [00:50<01:05,  8.94it/s]

Epoch 410, Loss: 0.18171200156211853


 42%|████▏     | 422/1000 [00:51<01:04,  8.97it/s]

Epoch 420, Loss: 0.17798687517642975


 43%|████▎     | 432/1000 [00:52<01:04,  8.87it/s]

Epoch 430, Loss: 0.17438049614429474


 44%|████▍     | 442/1000 [00:53<01:02,  8.97it/s]

Epoch 440, Loss: 0.1708919256925583


 45%|████▌     | 452/1000 [00:54<01:00,  8.99it/s]

Epoch 450, Loss: 0.16751761734485626


 46%|████▌     | 462/1000 [00:55<01:00,  8.84it/s]

Epoch 460, Loss: 0.164250910282135


 47%|████▋     | 472/1000 [00:57<00:59,  8.94it/s]

Epoch 470, Loss: 0.16109445691108704


 48%|████▊     | 482/1000 [00:58<00:57,  8.95it/s]

Epoch 480, Loss: 0.15804524719715118


 49%|████▉     | 492/1000 [00:59<00:57,  8.86it/s]

Epoch 490, Loss: 0.15511353313922882


 50%|█████     | 502/1000 [01:00<00:56,  8.87it/s]

Epoch 500, Loss: 0.15229925513267517


 51%|█████     | 512/1000 [01:01<00:55,  8.83it/s]

Epoch 510, Loss: 0.14959557354450226


 52%|█████▏    | 522/1000 [01:02<00:54,  8.84it/s]

Epoch 520, Loss: 0.14699828624725342


 53%|█████▎    | 532/1000 [01:03<00:54,  8.60it/s]

Epoch 530, Loss: 0.1445080190896988


 54%|█████▍    | 542/1000 [01:05<00:53,  8.64it/s]

Epoch 540, Loss: 0.14212477207183838


 55%|█████▌    | 552/1000 [01:06<00:49,  9.00it/s]

Epoch 550, Loss: 0.13984572887420654


 56%|█████▌    | 562/1000 [01:07<00:49,  8.86it/s]

Epoch 560, Loss: 0.13766968250274658


 57%|█████▋    | 572/1000 [01:08<00:49,  8.59it/s]

Epoch 570, Loss: 0.13559038937091827


 58%|█████▊    | 582/1000 [01:09<00:46,  8.90it/s]

Epoch 580, Loss: 0.1336088478565216


 59%|█████▉    | 592/1000 [01:10<00:45,  8.91it/s]

Epoch 590, Loss: 0.13171938061714172


 60%|██████    | 602/1000 [01:12<00:44,  8.92it/s]

Epoch 600, Loss: 0.12992200255393982


 61%|██████    | 612/1000 [01:13<00:43,  8.95it/s]

Epoch 610, Loss: 0.128212571144104


 62%|██████▏   | 622/1000 [01:14<00:42,  8.89it/s]

Epoch 620, Loss: 0.1265869289636612


 63%|██████▎   | 632/1000 [01:15<00:43,  8.51it/s]

Epoch 630, Loss: 0.12504146993160248


 64%|██████▍   | 642/1000 [01:16<00:40,  8.86it/s]

Epoch 640, Loss: 0.12357359379529953


 65%|██████▌   | 652/1000 [01:17<00:39,  8.84it/s]

Epoch 650, Loss: 0.12218963354825974


 66%|██████▌   | 662/1000 [01:19<00:38,  8.83it/s]

Epoch 660, Loss: 0.12087766081094742


 67%|██████▋   | 672/1000 [01:20<00:37,  8.78it/s]

Epoch 670, Loss: 0.11963577568531036


 68%|██████▊   | 682/1000 [01:21<00:35,  8.90it/s]

Epoch 680, Loss: 0.11846037954092026


 69%|██████▉   | 692/1000 [01:22<00:39,  7.89it/s]

Epoch 690, Loss: 0.11734902858734131


 70%|███████   | 702/1000 [01:23<00:33,  8.84it/s]

Epoch 700, Loss: 0.11630013585090637


 71%|███████   | 712/1000 [01:24<00:32,  9.00it/s]

Epoch 710, Loss: 0.11531035602092743


 72%|███████▏  | 722/1000 [01:26<00:35,  7.87it/s]

Epoch 720, Loss: 0.11437471210956573


 73%|███████▎  | 732/1000 [01:27<00:30,  8.77it/s]

Epoch 730, Loss: 0.11349364370107651


 74%|███████▍  | 742/1000 [01:28<00:36,  7.17it/s]

Epoch 740, Loss: 0.11266301572322845


 75%|███████▌  | 752/1000 [01:30<00:38,  6.48it/s]

Epoch 750, Loss: 0.1118796318769455


 76%|███████▌  | 762/1000 [01:31<00:29,  7.99it/s]

Epoch 760, Loss: 0.11113973706960678


 77%|███████▋  | 772/1000 [01:32<00:32,  7.12it/s]

Epoch 770, Loss: 0.1104462519288063


 78%|███████▊  | 782/1000 [01:34<00:31,  6.88it/s]

Epoch 780, Loss: 0.10979427397251129


 79%|███████▉  | 792/1000 [01:35<00:26,  7.93it/s]

Epoch 790, Loss: 0.10918031632900238


 80%|████████  | 802/1000 [01:37<00:26,  7.55it/s]

Epoch 800, Loss: 0.1086025983095169


 81%|████████  | 812/1000 [01:38<00:24,  7.64it/s]

Epoch 810, Loss: 0.10805918276309967


 82%|████████▏ | 822/1000 [01:40<00:24,  7.12it/s]

Epoch 820, Loss: 0.10754968225955963


 83%|████████▎ | 831/1000 [01:41<00:22,  7.52it/s]

Epoch 830, Loss: 0.1070694625377655


 84%|████████▍ | 842/1000 [01:42<00:21,  7.37it/s]

Epoch 840, Loss: 0.10661802440881729


 85%|████████▌ | 852/1000 [01:44<00:23,  6.24it/s]

Epoch 850, Loss: 0.10619306564331055


 86%|████████▌ | 862/1000 [01:45<00:20,  6.71it/s]

Epoch 860, Loss: 0.10579081624746323


 87%|████████▋ | 872/1000 [01:47<00:17,  7.48it/s]

Epoch 870, Loss: 0.10541205108165741


 88%|████████▊ | 882/1000 [01:48<00:13,  8.64it/s]

Epoch 880, Loss: 0.10505443066358566


 89%|████████▉ | 892/1000 [01:49<00:14,  7.70it/s]

Epoch 890, Loss: 0.10471536964178085


 90%|█████████ | 902/1000 [01:51<00:11,  8.53it/s]

Epoch 900, Loss: 0.10439637303352356


 91%|█████████ | 912/1000 [01:52<00:10,  8.46it/s]

Epoch 910, Loss: 0.10409361869096756


 92%|█████████▏| 922/1000 [01:53<00:08,  8.79it/s]

Epoch 920, Loss: 0.10380709916353226


 93%|█████████▎| 932/1000 [01:54<00:07,  8.72it/s]

Epoch 930, Loss: 0.10353383421897888


 94%|█████████▍| 942/1000 [01:55<00:06,  8.96it/s]

Epoch 940, Loss: 0.1032743826508522


 95%|█████████▌| 952/1000 [01:56<00:05,  8.77it/s]

Epoch 950, Loss: 0.10302683711051941


 96%|█████████▌| 962/1000 [01:58<00:04,  8.53it/s]

Epoch 960, Loss: 0.10279285907745361


 97%|█████████▋| 972/1000 [01:59<00:03,  7.67it/s]

Epoch 970, Loss: 0.10256482660770416


 98%|█████████▊| 982/1000 [02:00<00:02,  8.83it/s]

Epoch 980, Loss: 0.10234957188367844


 99%|█████████▉| 992/1000 [02:01<00:00,  8.65it/s]

Epoch 990, Loss: 0.10213912278413773


100%|██████████| 1000/1000 [02:02<00:00,  8.15it/s]

Final loss: 0.10195412486791611


In [16]:
labels = random.uniform(key, (10, 1), minval=-3, maxval=3)
labels = labels.squeeze()
labels

a = labels[3:6]
a

Array([-2.2756462, -1.8491192,  1.3320904], dtype=float32)

In [17]:
jnp.expand_dims(a, axis=-1)

Array([[-2.2756462],
       [-1.8491192],
       [ 1.3320904]], dtype=float32)

In [18]:
labels = random.uniform(key, (10, 3), minval=-3, maxval=3)
labels = labels.squeeze()
labels

a = labels[1:6, :]
a

Array([[-2.2756462 , -1.8491192 ,  1.3320904 ],
       [ 1.5926733 , -2.0847573 ,  2.7102375 ],
       [-2.8241372 , -2.4077368 ,  0.31885958],
       [-2.2533174 ,  0.5673723 ,  2.7569447 ],
       [ 1.1593628 ,  1.3445759 , -1.0910139 ]], dtype=float32)

In [19]:
a.shape

(5, 3)

In [20]:
jnp.expand_dims(a, axis=-1)

Array([[[-2.2756462 ],
        [-1.8491192 ],
        [ 1.3320904 ]],

       [[ 1.5926733 ],
        [-2.0847573 ],
        [ 2.7102375 ]],

       [[-2.8241372 ],
        [-2.4077368 ],
        [ 0.31885958]],

       [[-2.2533174 ],
        [ 0.5673723 ],
        [ 2.7569447 ]],

       [[ 1.1593628 ],
        [ 1.3445759 ],
        [-1.0910139 ]]], dtype=float32)

https://huggingface.co/blog/afmck/flax-tutorial
https://wandb.ai/jax-series/simple-training-loop/reports/Writing-a-Training-Loop-in-JAX-and-Flax--VmlldzoyMzA4ODEy