In [1]:
%load_ext autoreload
%autoreload 2

In [73]:
import jax.numpy as jnp
import jax
import jax.random as random
from flax import linen as nn
import tensorflow as tf
import optax
from tqdm import tqdm
from utils import DataLoader
from utils import MLP

In [74]:
key = random.PRNGKey(0) # chiave per random 

f_to_learn = lambda mu, k, l, x: jnp.sin(2*mu*jnp.pi*x) + k + jnp.exp(l*x)
N = 10000

key, subkey = random.split(key) # ogni volta, prima di usare la chiave, la devi dividere
x = random.uniform(subkey, (N,), minval=-10, maxval=10)
key, subkey = random.split(key)
mu = random.uniform(subkey, (N,), minval=-2, maxval=2)
key, subkey = random.split(key)
k = random.uniform(subkey, (N,), minval=-5, maxval=5)
key, subkey = random.split(key)
l = random.uniform(subkey, (N,), minval=-1, maxval=1)

y = f_to_learn(mu, k, l, x) # così generiamo artificialmente un dataset di N punti

In [75]:
X = jnp.stack([mu, k, l, x], axis=1)

In [76]:
X = jnp.stack([mu, k, l, x], axis=1)


split_idx = int(N * 0.8)
X_train, X_test = X[:split_idx], X[split_idx:]
y_train, y_test = y[:split_idx], y[split_idx:]

train_dataloader = DataLoader(X_train, y_train, batch_size=32, shuffle=True)
test_dataloader = DataLoader(X_test, y_test, batch_size=32, shuffle=False)


In [77]:
# Example of iterating through the DataLoader
for data, label in train_dataloader:
    print(data.shape, label.shape)
    break

(1, 32, 4) (1, 32)


In [78]:
targetnetwork = MLP(output_dim=1, hidden_dim=8, num_hidden_layers=1)

In [79]:
x = jnp.ones((1,1)) #Gli input sono SEMPRE (SEMPRE) nel formato (bathc_size, input_dim1, input_dim2, ..., input_dimN)
# In questo caso, batch_size=1, input_dim=1
key = jax.random.PRNGKey(0) # Bisogna sempre passare una key per inizializzare i pesi random
print(targetnetwork.tabulate(key, x)) # Visualizza la struttura del modello, con i pesi inizializzati


                               MLP Summary                               
┏━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓
┃ path    ┃ module ┃ inputs       ┃ outputs      ┃ params               ┃
┡━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩
│         │ MLP    │ float32[1,1] │ float32[1,1] │                      │
├─────────┼────────┼──────────────┼──────────────┼──────────────────────┤
│ Dense_0 │ Dense  │ float32[1,1] │ float32[1,8] │ bias: float32[8]     │
│         │        │              │              │ kernel: float32[1,8] │
│         │        │              │              │                      │
│         │        │              │              │ 16 (64 B)            │
├─────────┼────────┼──────────────┼──────────────┼──────────────────────┤
│ Dense_1 │ Dense  │ float32[1,8] │ float32[1,1] │ bias: float32[1]     │
│         │        │              │              │ kernel: float32[8,1] │
│         │        │              │  

In [80]:
hypernetwork = MLP(output_dim = 25, hidden_dim=8, num_hidden_layers=2) # 25 come i parametri del target network

## First try: only training a single network

In [155]:
key = jax.random.PRNGKey(0)
key, subkey = random.split(key)
toy_data = random.uniform(key, (1000, 1), minval=-3, maxval=3)
toy_label = f_to_learn(0.5, 1.0, 0.1, toy_data)
train_dataloader = DataLoader(toy_data, toy_label, batch_size=32, shuffle=True)

In [156]:
model = MLP(output_dim=1, hidden_dim=8, num_hidden_layers=1)

In [157]:
def mse_loss(preds, targets):
    return jnp.mean((preds - targets) ** 2)

optimizer = optax.adam(learning_rate=1e-3)
params = model.init(jax.random.PRNGKey(0), jnp.zeros((1, 1)))
opt_state = optimizer.init(params)
epochs = 1000

In [158]:
# HO CAPITO GLI ITERATORI LOL
it = iter(train_dataloader)
next(it)

(Array([[ 1.3251486 ],
        [ 1.7259715 ],
        [-1.4758916 ],
        [ 1.886148  ],
        [ 1.1210532 ],
        [-0.7078543 ],
        [ 2.0538847 ],
        [ 0.8367226 ],
        [-2.7543204 ],
        [-2.8492084 ],
        [-1.7900848 ],
        [-1.6452813 ],
        [ 0.29829955],
        [ 2.9617746 ],
        [ 1.2408056 ],
        [-0.33282137],
        [-0.01171947],
        [ 1.8245995 ],
        [-2.411188  ],
        [-2.432755  ],
        [ 0.43191075],
        [ 0.0389936 ],
        [-1.9057281 ],
        [ 2.5203166 ],
        [ 0.5336602 ],
        [ 1.9736738 ],
        [ 0.84615755],
        [-1.7945638 ],
        [ 2.6997864 ],
        [-1.15661   ],
        [-1.8660572 ],
        [ 2.6787364 ]], dtype=float32),
 Array([[1.2888119 ],
        [1.4299669 ],
        [2.8599188 ],
        [1.8574771 ],
        [1.7474318 ],
        [1.1373932 ],
        [2.3964787 ],
        [2.5780232 ],
        [1.0617999 ],
        [1.2958692 ],
        [2.4487953 ],
     

In [159]:
def train_step(model, params, opt_state, loss, optimizer, x, y, key=None):
    loss_fn = lambda p, x, y: loss(model.apply(p, x), y)
    loss, grad = jax.value_and_grad(loss_fn)(params, x, y)
    
    updates, opt_state = optimizer.update(grad, opt_state, params)
    params = optax.apply_updates(params, updates)

    return params, opt_state, loss

train_step = jax.jit(train_step, static_argnames=('model', 'loss', 'optimizer'))

for epoch in tqdm(range(epochs)):
    epoch_loss = 0.0
    for data, label in train_dataloader:
        params, opt_state, loss = train_step(model = model, params = params, opt_state = opt_state, loss = mse_loss, optimizer = optimizer, x = data, y = label)
        epoch_loss += loss
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {epoch_loss / len(train_dataloader)}")

print(f"Final loss: {epoch_loss / len(train_dataloader)}")

# TRAINA, POI VEDIAMO SE OVERFITTA CON UN TEST SET

  0%|          | 4/1000 [00:00<02:46,  5.97it/s]

Epoch 0, Loss: 3.7409934997558594


  1%|          | 12/1000 [00:01<01:16, 12.92it/s]

Epoch 10, Loss: 1.0597807168960571


  2%|▏         | 23/1000 [00:02<01:04, 15.23it/s]

Epoch 20, Loss: 0.8475213646888733


  3%|▎         | 33/1000 [00:02<00:50, 19.01it/s]

Epoch 30, Loss: 0.6785037517547607


  4%|▍         | 44/1000 [00:03<00:46, 20.45it/s]

Epoch 40, Loss: 0.5686261057853699


  5%|▌         | 53/1000 [00:03<00:45, 20.84it/s]

Epoch 50, Loss: 0.47054117918014526


  6%|▋         | 64/1000 [00:04<00:46, 20.15it/s]

Epoch 60, Loss: 0.43752285838127136


  8%|▊         | 75/1000 [00:04<00:44, 20.96it/s]

Epoch 70, Loss: 0.4153629541397095


  8%|▊         | 84/1000 [00:05<00:43, 21.19it/s]

Epoch 80, Loss: 0.39207300543785095


  9%|▉         | 93/1000 [00:05<00:42, 21.12it/s]

Epoch 90, Loss: 0.37217527627944946


 10%|█         | 105/1000 [00:06<00:43, 20.65it/s]

Epoch 100, Loss: 0.3569287359714508


 11%|█▏        | 113/1000 [00:06<00:45, 19.43it/s]

Epoch 110, Loss: 0.3435188829898834


 12%|█▏        | 123/1000 [00:07<00:45, 19.47it/s]

Epoch 120, Loss: 0.3312162160873413


 14%|█▎        | 135/1000 [00:07<00:40, 21.27it/s]

Epoch 130, Loss: 0.3203343451023102


 14%|█▍        | 144/1000 [00:08<00:41, 20.86it/s]

Epoch 140, Loss: 0.31050172448158264


 15%|█▌        | 153/1000 [00:08<00:40, 21.02it/s]

Epoch 150, Loss: 0.30179378390312195


 16%|█▋        | 165/1000 [00:09<00:40, 20.58it/s]

Epoch 160, Loss: 0.29402655363082886


 17%|█▋        | 174/1000 [00:09<00:43, 18.87it/s]

Epoch 170, Loss: 0.2871979773044586


 18%|█▊        | 184/1000 [00:10<00:40, 20.35it/s]

Epoch 180, Loss: 0.28105685114860535


 19%|█▉        | 193/1000 [00:10<00:38, 21.06it/s]

Epoch 190, Loss: 0.2754061222076416


 20%|██        | 205/1000 [00:11<00:36, 21.78it/s]

Epoch 200, Loss: 0.2701038718223572


 21%|██▏       | 214/1000 [00:11<00:36, 21.59it/s]

Epoch 210, Loss: 0.2651025056838989


 22%|██▏       | 223/1000 [00:12<00:35, 21.62it/s]

Epoch 220, Loss: 0.2603227496147156


 23%|██▎       | 234/1000 [00:12<00:36, 20.96it/s]

Epoch 230, Loss: 0.25575998425483704


 24%|██▍       | 243/1000 [00:13<00:38, 19.69it/s]

Epoch 240, Loss: 0.2513675391674042


 26%|██▌       | 255/1000 [00:13<00:37, 19.96it/s]

Epoch 250, Loss: 0.2471306473016739


 26%|██▋       | 264/1000 [00:14<00:34, 21.12it/s]

Epoch 260, Loss: 0.24303525686264038


 27%|██▋       | 274/1000 [00:14<00:36, 19.81it/s]

Epoch 270, Loss: 0.23906444013118744


 28%|██▊       | 285/1000 [00:15<00:34, 20.82it/s]

Epoch 280, Loss: 0.23521246016025543


 29%|██▉       | 293/1000 [00:15<00:35, 19.78it/s]

Epoch 290, Loss: 0.23146076500415802


 30%|███       | 304/1000 [00:16<00:35, 19.78it/s]

Epoch 300, Loss: 0.22765040397644043


 31%|███       | 312/1000 [00:16<00:41, 16.50it/s]

Epoch 310, Loss: 0.22316774725914001


 32%|███▏      | 324/1000 [00:17<00:36, 18.70it/s]

Epoch 320, Loss: 0.21897540986537933


 34%|███▎      | 335/1000 [00:17<00:34, 19.17it/s]

Epoch 330, Loss: 0.2147229164838791


 34%|███▍      | 343/1000 [00:18<00:33, 19.64it/s]

Epoch 340, Loss: 0.2104337066411972


 35%|███▌      | 353/1000 [00:18<00:32, 20.01it/s]

Epoch 350, Loss: 0.2061324268579483


 36%|███▋      | 365/1000 [00:19<00:29, 21.17it/s]

Epoch 360, Loss: 0.20186805725097656


 37%|███▋      | 374/1000 [00:19<00:29, 21.06it/s]

Epoch 370, Loss: 0.19766759872436523


 38%|███▊      | 383/1000 [00:20<00:29, 20.76it/s]

Epoch 380, Loss: 0.19353732466697693


 40%|███▉      | 395/1000 [00:20<00:28, 21.13it/s]

Epoch 390, Loss: 0.1895001232624054


 40%|████      | 404/1000 [00:21<00:32, 18.58it/s]

Epoch 400, Loss: 0.18555985391139984


 41%|████▏     | 414/1000 [00:21<00:34, 16.77it/s]

Epoch 410, Loss: 0.18171197175979614


 42%|████▏     | 424/1000 [00:22<00:33, 17.16it/s]

Epoch 420, Loss: 0.17798686027526855


 43%|████▎     | 434/1000 [00:23<00:28, 19.99it/s]

Epoch 430, Loss: 0.17438045144081116


 44%|████▍     | 444/1000 [00:23<00:26, 20.82it/s]

Epoch 440, Loss: 0.17089194059371948


 46%|████▌     | 455/1000 [00:24<00:26, 20.31it/s]

Epoch 450, Loss: 0.16751764714717865


 46%|████▋     | 464/1000 [00:24<00:26, 20.58it/s]

Epoch 460, Loss: 0.164250910282135


 47%|████▋     | 473/1000 [00:25<00:29, 17.99it/s]

Epoch 470, Loss: 0.16109448671340942


 48%|████▊     | 483/1000 [00:25<00:29, 17.24it/s]

Epoch 480, Loss: 0.15804529190063477


 49%|████▉     | 493/1000 [00:26<00:30, 16.59it/s]

Epoch 490, Loss: 0.15511353313922882


 50%|█████     | 505/1000 [00:26<00:25, 19.23it/s]

Epoch 500, Loss: 0.15229925513267517


 52%|█████▏    | 515/1000 [00:27<00:24, 20.00it/s]

Epoch 510, Loss: 0.14959557354450226


 52%|█████▏    | 524/1000 [00:27<00:24, 19.63it/s]

Epoch 520, Loss: 0.14699828624725342


 53%|█████▎    | 532/1000 [00:28<00:27, 17.28it/s]

Epoch 530, Loss: 0.14450803399085999


 55%|█████▍    | 545/1000 [00:29<00:27, 16.52it/s]

Epoch 540, Loss: 0.14212480187416077


 55%|█████▌    | 552/1000 [00:29<00:25, 17.34it/s]

Epoch 550, Loss: 0.13984572887420654


 56%|█████▋    | 564/1000 [00:30<00:27, 16.03it/s]

Epoch 560, Loss: 0.13766969740390778


 57%|█████▋    | 572/1000 [00:31<00:38, 11.08it/s]

Epoch 570, Loss: 0.13559043407440186


 58%|█████▊    | 582/1000 [00:32<00:37, 11.01it/s]

Epoch 580, Loss: 0.1336088627576828


 59%|█████▉    | 592/1000 [00:32<00:37, 10.89it/s]

Epoch 590, Loss: 0.13171938061714172


 60%|██████    | 602/1000 [00:33<00:29, 13.34it/s]

Epoch 600, Loss: 0.12992198765277863


 61%|██████    | 612/1000 [00:34<00:30, 12.92it/s]

Epoch 610, Loss: 0.12821254134178162


 62%|██████▏   | 622/1000 [00:35<00:30, 12.22it/s]

Epoch 620, Loss: 0.1265869438648224


 63%|██████▎   | 632/1000 [00:36<00:43,  8.55it/s]

Epoch 630, Loss: 0.12504146993160248


 64%|██████▍   | 643/1000 [00:37<00:26, 13.44it/s]

Epoch 640, Loss: 0.12357354909181595


 65%|██████▌   | 653/1000 [00:38<00:22, 15.25it/s]

Epoch 650, Loss: 0.12218959629535675


 66%|██████▋   | 663/1000 [00:38<00:22, 14.85it/s]

Epoch 660, Loss: 0.12087760865688324


 67%|██████▋   | 674/1000 [00:39<00:20, 16.11it/s]

Epoch 670, Loss: 0.11963576823472977


 68%|██████▊   | 684/1000 [00:40<00:19, 15.93it/s]

Epoch 680, Loss: 0.11846034973859787


 69%|██████▉   | 692/1000 [00:40<00:23, 13.24it/s]

Epoch 690, Loss: 0.11734902113676071


 70%|███████   | 705/1000 [00:41<00:18, 16.23it/s]

Epoch 700, Loss: 0.11630012840032578


 72%|███████▏  | 715/1000 [00:42<00:14, 19.48it/s]

Epoch 710, Loss: 0.11531030386686325


 72%|███████▎  | 725/1000 [00:42<00:13, 20.63it/s]

Epoch 720, Loss: 0.11437468230724335


 73%|███████▎  | 733/1000 [00:42<00:14, 18.49it/s]

Epoch 730, Loss: 0.11349362134933472


 74%|███████▍  | 744/1000 [00:43<00:12, 19.71it/s]

Epoch 740, Loss: 0.11266295611858368


 75%|███████▌  | 754/1000 [00:44<00:11, 20.66it/s]

Epoch 750, Loss: 0.11187957227230072


 76%|███████▋  | 763/1000 [00:44<00:11, 20.92it/s]

Epoch 760, Loss: 0.11113971471786499


 78%|███████▊  | 775/1000 [00:45<00:10, 21.44it/s]

Epoch 770, Loss: 0.11044617742300034


 78%|███████▊  | 784/1000 [00:45<00:10, 20.16it/s]

Epoch 780, Loss: 0.1097942441701889


 79%|███████▉  | 793/1000 [00:45<00:09, 20.97it/s]

Epoch 790, Loss: 0.10918030142784119


 80%|████████  | 802/1000 [00:46<00:09, 20.48it/s]

Epoch 800, Loss: 0.10860259085893631


 81%|████████▏ | 813/1000 [00:47<00:11, 16.95it/s]

Epoch 810, Loss: 0.10805917531251907


 82%|████████▏ | 824/1000 [00:47<00:09, 18.70it/s]

Epoch 820, Loss: 0.10754965245723724


 83%|████████▎ | 834/1000 [00:48<00:08, 20.14it/s]

Epoch 830, Loss: 0.1070694550871849


 84%|████████▍ | 843/1000 [00:48<00:08, 17.75it/s]

Epoch 840, Loss: 0.10661796480417252


 86%|████████▌ | 855/1000 [00:49<00:07, 18.28it/s]

Epoch 850, Loss: 0.10619302839040756


 86%|████████▋ | 865/1000 [00:49<00:06, 20.26it/s]

Epoch 860, Loss: 0.10579082369804382


 87%|████████▋ | 873/1000 [00:50<00:06, 20.27it/s]

Epoch 870, Loss: 0.1054120659828186


 88%|████████▊ | 884/1000 [00:50<00:05, 19.56it/s]

Epoch 880, Loss: 0.10505438596010208


 89%|████████▉ | 893/1000 [00:51<00:06, 16.88it/s]

Epoch 890, Loss: 0.10471535474061966


 90%|█████████ | 904/1000 [00:52<00:05, 18.15it/s]

Epoch 900, Loss: 0.10439637303352356


 91%|█████████▏| 914/1000 [00:52<00:05, 16.74it/s]

Epoch 910, Loss: 0.10409360378980637


 92%|█████████▏| 923/1000 [00:53<00:04, 18.20it/s]

Epoch 920, Loss: 0.10380709171295166


 93%|█████████▎| 934/1000 [00:53<00:03, 20.50it/s]

Epoch 930, Loss: 0.1035337969660759


 94%|█████████▍| 942/1000 [00:54<00:02, 20.55it/s]

Epoch 940, Loss: 0.1032743752002716


 95%|█████████▌| 953/1000 [00:54<00:02, 20.29it/s]

Epoch 950, Loss: 0.1030268520116806


 96%|█████████▋| 965/1000 [00:55<00:01, 21.04it/s]

Epoch 960, Loss: 0.10279282927513123


 98%|█████████▊| 975/1000 [00:55<00:01, 18.79it/s]

Epoch 970, Loss: 0.10256482660770416


 98%|█████████▊| 985/1000 [00:56<00:00, 20.64it/s]

Epoch 980, Loss: 0.10234955698251724


 99%|█████████▉| 994/1000 [00:56<00:00, 20.56it/s]

Epoch 990, Loss: 0.10213910043239594


100%|██████████| 1000/1000 [00:57<00:00, 17.53it/s]

Final loss: 0.1019541546702385


In [140]:
labels = random.uniform(key, (10, 1), minval=-3, maxval=3)
labels = labels.squeeze()
labels

a = labels[3:6]
a

Array([-2.2756462, -1.8491192,  1.3320901], dtype=float32)

In [126]:
jnp.expand_dims(a, axis=-1)

Array([[-2.2756462],
       [-1.8491192],
       [ 1.3320901]], dtype=float32)

In [138]:
labels = random.uniform(key, (10, 3), minval=-3, maxval=3)
labels = labels.squeeze()
labels

a = labels[1:6, :]
a

Array([[-2.2756462 , -1.8491192 ,  1.3320901 ],
       [ 1.5926735 , -2.0847573 ,  2.7102377 ],
       [-2.8241372 , -2.4077368 ,  0.31885958],
       [-2.2533174 ,  0.5673723 ,  2.7569447 ],
       [ 1.159363  ,  1.3445756 , -1.0910139 ]], dtype=float32)

In [139]:
a.shape

(5, 3)

In [130]:
jnp.expand_dims(a, axis=-1)

Array([[[-2.2756462 ],
        [-1.8491192 ],
        [ 1.3320901 ]],

       [[ 1.5926735 ],
        [-2.0847573 ],
        [ 2.7102377 ]],

       [[-2.8241372 ],
        [-2.4077368 ],
        [ 0.31885958]],

       [[-2.2533174 ],
        [ 0.5673723 ],
        [ 2.7569447 ]],

       [[ 1.159363  ],
        [ 1.3445756 ],
        [-1.0910139 ]]], dtype=float32)

https://huggingface.co/blog/afmck/flax-tutorial
https://wandb.ai/jax-series/simple-training-loop/reports/Writing-a-Training-Loop-in-JAX-and-Flax--VmlldzoyMzA4ODEy